# Generated by Django 4.1.1 on 2022-09-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
