# Generated by Django 4.1.1 on 2022-09-30 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0002_rename_apellido_familiar_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
