# Generated by Django 4.1.1 on 2022-09-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0003_familiar_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
    ]
